### ISSUE TITLE
Create new page - bad blog operation

### ISSUE THREAD

**Issue by nicopresto** [dotskapes/dotSkapes#14]
I get a bad blog operation when I try to create a new page via wiki syntax.

For example, editing app_git/wiki/case/cases/edit with:
"Testing a link to [[another page page:page2]]"

Creates a link
app/wiki/case/page2

This should probably redirect to edit new page

**Comment by zack-krejci** [comment]
[[another page page:page2]] now points to an empty page and "create page" message if you have permissions to create it.
